config/routes.rb
require 'lockup'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Lockup::Engine, at: '/lockup' if Rails.env.production?
  mount Lookbook::Engine, at: '/lookbook' if Rails.env.development?

  if Rails.configuration.x.cypress
    namespace :cypress do
      delete 'cleanup', to: 'cleanup#destroy'
    end
  end

  get '/manifest.v1.webmanifest', to: 'statics#manifest', as: :webmanifest

  root to: 'main#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cypress/cleanup_controller.rb
module Cypress
  class CleanupController < ActionController::Base
    def destroy
      return unless Rails.configuration.x.cypress

      tables = ActiveRecord::Base.connection.tables
      tables.delete 'schema_migrations'
      tables.each do |t|
        ActiveRecord::Base.connection.execute("TRUNCATE #{t} CASCADE")
      end

      head :ok
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    def index
    end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  skip_before_action :check_for_lockup, raise: false

  def manifest
    expires_in 1.day

    respond_to { |format| format.webmanifest { render } }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def cp(path)
        return true if current_page?(path)
    end
end

app/helpers/heroicon_helper.rb
module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= tag.meta charset: 'utf-8' %>
    <%= tag.title 'Gaizka Urdangarin Template' %>
    <%= tag.meta content: 'GaizkaU', name: 'description' %>
    <%= tag.meta content: 'width=device-width,initial-scale=1', name: 'viewport' %>
    <%= tag.meta content: 'yes', name: 'mobile-web-app-capable' %>
    <%= tag.meta content: 'GaizkaU', name: 'application-name' %>
    <%= tag.meta content: '#991c1c', name: 'theme-color' %>
    <%= tag.meta content: '#ffc40d', name: 'msapplication-TileColor' %>
    <%= tag.meta content: 'yes', name: 'apple-mobile-web-app-capable' %>
    <%= tag.meta content: 'GaizkaU', name: 'apple-mobile-web-app-title' %>
    <%= tag.meta content: 'black', name: 'apple-mobile-web-app-status-bar-style' %>
    <%= tag.meta content: Rails.configuration.x.git.commit_version, name: 'git-commit-version' %>
    <%= tag.meta content: Rails.configuration.x.git.commit_time, name: 'git-commit-time' %>
    <%= tag.meta name: 'app-host', content: Rails.configuration.x.app_host %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= tag.link href: asset_path('/apple-touch-icon.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180' %>
    <%= tag.link href: asset_path('/favicon-32x32.png'),    rel: 'icon',             type: 'image/png', sizes: '32x32' %>
    <%= tag.link href: asset_path('/favicon-16x16.png'),    rel: 'icon',             type: 'image/png', sizes: '16x16' %>
    <%= tag.link href: asset_path('/safari-pinned-tab.svg'),rel: 'mask-icon',        color: '#d30001' %>
    <%= tag.link href: webmanifest_path, rel: 'manifest' %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application', 'data-turbo-track': 'reload' %>
    <%= vite_stylesheet_tag 'application', 'data-turbo-track': 'reload' %>
  </head>
  <body class="dark:bg-gray-800 bg-slate-50">
    <div class="max-w-7xl px-4 sm:px-6 lg:px-8 mx-auto">
      <%= render FlashAlert::Component.new %>
      <%= render Navigation::Component.new do |nav| %>
        <% nav.nav_links [
          { name: 'Home', href: root_path }, \
          { name: 'Help', href: '#' }
        ]%>
      <% end %>
      <main class="dark:bg-gray-700 dark:text-white bg-white shadow-xl rounded-3xl p-5 sm:p-8 lg:p-10">
        <%= yield %>
      </main>
      <%= render AppFooter::Component.new class: 'relative mt-2 mb-6 lg:px-0 lg:mr-16 lg:ml-96 lg:max-w-5xl' %>
    </div>
  </body>
</html>

app/views/layouts/preview.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="width=device-width,initial-scale=1" name="viewport" />
    <title>Component Preview</title>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application', 'data-turbo-track': 'reload' %>
    <%= vite_stylesheet_tag 'application', 'data-turbo-track': 'reload' %>
  </head><body>
    <div class="p-4">
      <%= yield %>
    </div>
  </body></html>

app/views/main/index.html.erb
<div class="flex flex-col sm:flex-row sm:items-center mb-8">
  <h1 class="dark:text-white uppercase tracking-wider font-semibold flex-auto">Inicio</h1>
</div>
<div>
    <h1 class="dark:text-white text-3xl font-semibold text-center">What are we building today?</h2>
</div>

app/views/statics/manifest.webmanifest.erb
{
  "name": "GaizkaU",
  "short_name": "GaizkaU",
  "start_url": "/",
  "display": "standalone",
  "orientation": "portrait",
  "icons": [
    {
      "src": "<%= asset_path('/android-chrome-192x192.png') %>",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "<%= asset_path('/android-chrome-512x512.png') %>",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "<%= asset_path('/maskable_icon_x384.png') %>",
      "sizes": "384x384",
      "type": "image/png",
      "purpose": "maskable"
    }
  ],
  "theme_color": "#991c1c",
  "background_color": "#ffffff"
}